/**
 * SDK Alert Methods Test
 * Tests all alert-related SDK methods against live ARO server
 */

import { AgentRateOracle } from '../src/sdk/client.js';

const BASE_URL = 'http://localhost:3402';

// Create test agent first (API key will be generated by server)
async function createTestAgent() {
  const response = await fetch(`${BASE_URL}/v1/agents`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: 'SDK Test Agent ' + Date.now()
    })
  });

  if (!response.ok) {
    throw new Error(`Failed to create test agent: ${response.status}`);
  }

  const data = await response.json();
  return data.data; // { id, name, apiKey }
}

async function runTests() {
  console.log('🧪 SDK Alert Methods Test Suite\n');

  // Create test agent
  console.log('📋 Setup: Creating test agent...');
  const agent = await createTestAgent();
  console.log(`✓ Test agent created: ${agent.name} (ID: ${agent.id})`);
  console.log(`  API Key: ${agent.apiKey}`);

  // Initialize SDK client with auth (use server-generated API key)
  const aro = new AgentRateOracle({
    baseUrl: BASE_URL,
    apiKey: agent.apiKey,
    agentId: agent.id
  });

  let createdAlertId;

  // Test 1: createAlert()
  console.log('\n📝 Test 1: createAlert() - create price threshold alert');
  try {
    const alert = await aro.createAlert({
      alertType: 'price_threshold',
      targetSkill: 'text-generation/chat',
      maxPrice: 0.015,
      notifyMethod: 'webhook',
      webhookUrl: 'https://webhook.site/test-sdk'
    });

    if (!alert.id || alert.status !== 'active') {
      throw new Error('Invalid alert response');
    }

    createdAlertId = alert.id;
    console.log(`✓ Alert created: ID=${alert.id}, status=${alert.status}, type=${alert.alertType}`);
  } catch (error) {
    console.error(`✗ Test 1 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 2: getAlerts()
  console.log('\n📋 Test 2: getAlerts() - list all alerts');
  try {
    const alerts = await aro.getAlerts();

    if (!Array.isArray(alerts) || alerts.length === 0) {
      throw new Error('Expected non-empty alerts array');
    }

    const foundAlert = alerts.find(a => a.id === createdAlertId);
    if (!foundAlert) {
      throw new Error('Created alert not found in list');
    }

    console.log(`✓ Retrieved ${alerts.length} alert(s)`);
    console.log(`  - Alert #${foundAlert.id}: ${foundAlert.alertType}, target=${foundAlert.targetSkill || foundAlert.targetProvider}, status=${foundAlert.status}`);
  } catch (error) {
    console.error(`✗ Test 2 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 3: updateAlert() - pause alert
  console.log('\n⏸️  Test 3: updateAlert() - pause alert');
  try {
    const updated = await aro.updateAlert(createdAlertId, 'paused');

    if (updated.id !== createdAlertId || updated.status !== 'paused') {
      throw new Error('Alert status not updated correctly');
    }

    console.log(`✓ Alert #${updated.id} paused successfully`);
  } catch (error) {
    console.error(`✗ Test 3 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 4: updateAlert() - reactivate alert
  console.log('\n▶️  Test 4: updateAlert() - reactivate alert');
  try {
    const updated = await aro.updateAlert(createdAlertId, 'active');

    if (updated.status !== 'active') {
      throw new Error('Alert not reactivated');
    }

    console.log(`✓ Alert #${updated.id} reactivated successfully`);
  } catch (error) {
    console.error(`✗ Test 4 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 5: getAlertHistory()
  console.log('\n📊 Test 5: getAlertHistory() - get trigger history');
  try {
    const history = await aro.getAlertHistory(createdAlertId);

    if (!Array.isArray(history)) {
      throw new Error('Expected history array');
    }

    console.log(`✓ Retrieved alert history: ${history.length} trigger(s)`);
  } catch (error) {
    console.error(`✗ Test 5 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 6: deleteAlert()
  console.log('\n🗑️  Test 6: deleteAlert() - delete alert');
  try {
    const result = await aro.deleteAlert(createdAlertId);

    if (!result.success) {
      throw new Error('Delete operation failed');
    }

    console.log(`✓ Alert #${createdAlertId} deleted successfully`);
  } catch (error) {
    console.error(`✗ Test 6 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 7: Verify alert deleted
  console.log('\n🔍 Test 7: Verify deleted alert not in list');
  try {
    const alerts = await aro.getAlerts();
    const stillExists = alerts.find(a => a.id === createdAlertId);

    if (stillExists) {
      throw new Error('Deleted alert still exists in list');
    }

    console.log(`✓ Alert correctly removed from list`);
  } catch (error) {
    console.error(`✗ Test 7 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 8: Validation tests
  console.log('\n🛡️  Test 8: Client-side validation (missing API key)');
  try {
    const unauthClient = new AgentRateOracle({ baseUrl: BASE_URL }); // No API key

    try {
      await unauthClient.createAlert({
        alertType: 'price_drop',
        targetSkill: 'text-generation/chat',
        notifyMethod: 'webhook',
        webhookUrl: 'https://test.com'
      });
      throw new Error('Should have thrown authentication error');
    } catch (error) {
      if (!error.message.includes('API key required')) {
        throw new Error(`Wrong error: ${error.message}`);
      }
      console.log(`✓ Correctly throws error: "${error.message}"`);
    }
  } catch (error) {
    console.error(`✗ Test 8 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 9: Validation - missing required fields
  console.log('\n🛡️  Test 9: Client-side validation (missing alertType)');
  try {
    try {
      await aro.createAlert({
        targetSkill: 'text-generation/chat',
        notifyMethod: 'webhook',
        webhookUrl: 'https://test.com'
      });
      throw new Error('Should have thrown validation error');
    } catch (error) {
      if (!error.message.includes('alertType is required')) {
        throw new Error(`Wrong error: ${error.message}`);
      }
      console.log(`✓ Correctly throws error: "${error.message}"`);
    }
  } catch (error) {
    console.error(`✗ Test 9 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 10: Validation - invalid status
  console.log('\n🛡️  Test 10: Client-side validation (invalid status)');
  try {
    const newAlert = await aro.createAlert({
      alertType: 'price_drop',
      targetSkill: 'text-generation/chat',
      notifyMethod: 'webhook',
      webhookUrl: 'https://test.com'
    });

    try {
      await aro.updateAlert(newAlert.id, 'invalid_status');
      throw new Error('Should have thrown validation error');
    } catch (error) {
      if (!error.message.includes('status must be one of')) {
        throw new Error(`Wrong error: ${error.message}`);
      }
      console.log(`✓ Correctly throws error: "${error.message}"`);
    }

    // Clean up
    await aro.deleteAlert(newAlert.id);
  } catch (error) {
    console.error(`✗ Test 10 failed: ${error.message}`);
    process.exit(1);
  }

  // Test 11: connectWebSocket() - basic setup test (skip actual connection for now)
  console.log('\n🔌 Test 11: connectWebSocket() - validation check');
  try {
    // Test validation (no actual connection needed)
    const noApiKeyClient = new AgentRateOracle({ baseUrl: BASE_URL });
    try {
      await noApiKeyClient.connectWebSocket(() => {});
      throw new Error('Should require API key');
    } catch (error) {
      if (!error.message.includes('API key required')) {
        throw error;
      }
      console.log(`✓ WebSocket validation works (API key required)`);
    }

    // Test callback validation
    try {
      await aro.connectWebSocket('not-a-function');
      throw new Error('Should require callback function');
    } catch (error) {
      if (!error.message.includes('callback function is required')) {
        throw error;
      }
      console.log(`✓ WebSocket validation works (callback required)`);
    }
  } catch (error) {
    console.error(`✗ Test 11 failed: ${error.message}`);
    process.exit(1);
  }

  console.log('\n✅ All 11 SDK alert method tests passed!\n');
  console.log('Summary:');
  console.log('  ✓ createAlert() - creates alert with validation');
  console.log('  ✓ getAlerts() - lists all alerts for authenticated agent');
  console.log('  ✓ updateAlert() - updates alert status (pause/resume)');
  console.log('  ✓ deleteAlert() - deletes alert');
  console.log('  ✓ getAlertHistory() - retrieves trigger history');
  console.log('  ✓ connectWebSocket() - validates authentication requirements');
  console.log('  ✓ Client-side validation working (API key, required fields, enums)');
  console.log('  ✓ Error handling working (throws descriptive errors)');
}

// Run tests
runTests().catch(error => {
  console.error('\n💥 Test suite error:', error);
  process.exit(1);
});
